apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: reports-repo
  name: reports-repo
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: reports-repo
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None